<a href="https://colab.research.google.com/github/KiruthikaKuppusaamy/NumPy/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NumPy Tutorial***

### NumPy, established in 2005 as a Python library, specializes in performing numerical computations and is primarily employed for array manipulation tasks.

# **Applications of NumPy**

Machine Learning

Data Science

Image and Signal Processing

Scientific Computing

Quantum Computing

# **Advantages of Numpy**

In Python, while lists are commonly used for handling arrays, they may not be efficiently optimized for large-scale array operations. NumPy arrays, on the other hand, are specifically designed for complex mathematical and statistical computations.

NumPy is extensively integrated with other Python libraries such as Pandas, Scipy, scikit-learn, and others.

# **Import NumPy in Python**

In [ ]:
import numpy

In [70]:
import numpy as np

# **NumPy Array Creation**

An array enables the storage of multiple values within a single data structure.

whereas NumPy array shares similarities with a list but offers advantages like enhanced speed and memory efficiency.

array object in NumPy is called ndarray.

## Method 1 : Creating Numpy Array using **List** or **Tuple** directly

In [ ]:
import numpy
ksr = numpy.array([1,2,3,4,5])
print(ksr)

[1 2 3 4 5]


## Method 2 : Creating Numpy Array using **List** through variable

In [ ]:
# import the library
import numpy as np

# create list
ksrct = [10,20,30,40,50]

# create numpy array using list
nparr = np.array(ksrct)

# alternate is, v can print directly
np.array

<function numpy.array>

In [ ]:
# print the numpy array
print(nparr)

[10 20 30 40 50]


## Method 3 : Create an Array using np.zeros()
creating an array with elements all initialized to 0

In [ ]:
zeroarr = np.zeros(5)
zeroarr

array([0., 0., 0., 0., 0.])

# Method 4 : Create an Array using np.arange()
returns an array with values within a specified interval

In [ ]:
r1arr = np.arange(5)
print(r1arr)

[0 1 2 3 4]


In [ ]:
r2arr = np.arange(1,10)
print(r2arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
r3arr = np.arange(1,10,2)
print(r3arr)

[1 3 5 7 9]


In [ ]:
r4arr = np.arange(10,1,-1)
print(r4arr)

[10  9  8  7  6  5  4  3  2]


# Create an Array using np.random.rand()
create an array of random numbers

generates a different output each time we run it

In [ ]:
rnarr = np.random.rand(10)
print(rnarr)

[0.42529435 0.44967376 0.60985522 0.28589096 0.71627043 0.05011958
 0.54194086 0.03287408 0.33564862 0.79480123]


# Method 5: Create an Array using empty()
create an empty NumPy array

output of the code, is actually not empty, it has some values in it.

NumPy will try to add some value to it. The values stored in the array are arbitrary and have no significance

In [ ]:
earr = np.empty(4)
print(earr)

[4.66910391e-310 0.00000000e+000 5.63234836e-322 5.63234836e-322]


--------------------------------------------------------------------------------------------------------------------

# NumPy N-D Array Creation
NumPy extends beyond 1-D arrays, supporting arrays of multiple dimensions, commonly referred to as N-dimensional arrays or ndarrays.
n represents number of dimensions

2D array represents a table with rows and columns

3D array represents a cube with width, height, and depth

## Create a 2-D NumPy Array

In [ ]:
twoarr = np.array([[1,2,3],[4,5,6]])
print(twoarr)


[[1 2 3]
 [4 5 6]]


In [ ]:
lst1 = [10,20,30]
lst2 = [40,50,60]
toarr = np.array([lst1,lst2])
print(toarr)

[[10 20 30]
 [40 50 60]]


## Create a 3-D NumPy Array
1. fix slice or depth

```
array([])
array([
       [],
       [],
       []
      ])
```
  
2. fix row or height
  
```
 array([
          [ [],[],[] ],

          [ [],[],[] ],

          [ [],[],[] ]

       ])
```


3. enter column or width

```
array([
          [[1,2],[3,4],[5,6]],

          [[0,0],[1,1],[2,2]],

          [[7,8],[7,9],[8,9]]

     ])
```




### width = 3, height = 3 , depth = 3

In [ ]:
th1arr = np.array([[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,223],[231,232,233]],[[311,312,313],[321,322,323],[331,332,333]]])
print(th1arr)

[[[111 112 113]
  [121 122 123]
  [131 132 133]]

 [[211 212 213]
  [221 222 223]
  [231 232 233]]

 [[311 312 313]
  [321 322 323]
  [331 332 333]]]


### width = 2, height = 3 , depth = 4

In [ ]:
th2arr = np.array([[[11,12,13,14],[21,22,23,24],[31,32,33,34]],[[41,42,43,44],[51,52,53,54],[61,62,63,64]]])
print(th2arr)

[[[11 12 13 14]
  [21 22 23 24]
  [31 32 33 34]]

 [[41 42 43 44]
  [51 52 53 54]
  [61 62 63 64]]]


### Create 2D and 3D array with zeros(), random.rand()

In [ ]:
# zeros - 2D
z2 = np.zeros((3,2))
print(z2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# zeros - 3D
z3 = np.zeros((2,3,4))
print(z3)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# rand - 1D
r1 = np.random.rand(3)
print("1D array")
print(r1)
print("______________")

# rand - 1D
r2 = np.random.rand(2,3)
print("2D array")
print(r2)
print("______________")

# rand - 3D
r3 = np.random.rand(2,3,4)
print("3D array")
print(r3)

1D array
[0.63189772 0.27443576 0.89571231]
______________
2D array
[[0.80289119 0.03148871 0.67142762]
 [0.54080211 0.05199389 0.10942536]]
______________
3D array
[[[0.78555022 0.7224587  0.62612001 0.3677709 ]
  [0.00458192 0.61748249 0.78113768 0.87068929]
  [0.86783317 0.35482804 0.02201682 0.71148422]]

 [[0.01539332 0.47325016 0.43876735 0.59968714]
  [0.13593693 0.68621829 0.55561358 0.60560297]
  [0.67275179 0.17311727 0.8618296  0.74484504]]]


### ones(), full()
create N-D arrays filled with all zeros

create a multidimensional array with a specified value.

In [ ]:
# ones - 1D
o1 = np.ones((2))
print(o1)

[1. 1.]


In [ ]:
# ones - 2D
o2 = np.ones((2,3))
print(o2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# ones - 3D
o3 = np.ones((2,3,4))
print(o3)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# full - 1D
f1 = np.full((3),6)
print(f1)

[6 6 6]


In [ ]:
# full - 2D
f2 = np.full((3,4),6)
print(f2)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
# full - 3D
f3 = np.full((2,3,4),6)
print(f3)

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


# NumPy Data Types
int8, int16, int32, int64 - signed integer types with different bit sizes

uint8, uint16, uint32, uint64 - unsigned integer types with different bit sizes

float32, float64 - floating-point types with different precision levels

complex64, complex128 - complex number types with different precision levels

### to check data type - dtype()


In [ ]:
intarr = np.array([1,2,3,4,5])
print("Data type of intarr is : ",intarr.dtype)

floarr = np.array([-1,4.2,3,-4,-5])
print("Data type of floarr is : ",floarr.dtype)

comarr = np.array([1+2j,5+6j,7])
print("Data type of comarr is : ",comarr.dtype)

Data type of intarr is :  int64
Data type of floarr is :  float64
Data type of comarr is :  complex128


### NumPy Type Conversion - astype()

In [ ]:
iarr = np.array([2,4,6])
farr = iarr.astype('float')

print("Data type of ",iarr,"   is",iarr.dtype)
print("Data type of ",farr,"is",farr.dtype)

Data type of  [2 4 6]    is int64
Data type of  [2. 4. 6.] is float64


# NumPy Array Attributes
accessed with . notation
### ndim, size, dtype, shape, itemsize, data

In [ ]:
# ndim      - returns number of dimension of the array
a1 = np.array([[2,3,4],[5,6,7]])
print("Array is \n",a1)
print("\nDimension of array  is             : ",a1.ndim)

# size	    - returns number of elements in the array
print("No of elements in array is         : ",a1.size)

# dtype     - returns data type of the elements in the array
print("Data type of array is              : ",a1.dtype)

# shape	    - returns the size of the array in each dimension
print("Size of array in each dimension is : ",a1.shape)

# itemsize	- returns the size (in bytes) of each elements in the array
print("Size (in bytes) of array is        : ",a1.itemsize)

# data	    - returns the buffer containing actual elements of the array in memory
print("Memory location  of array is       : ",a1.data)

Array is 
 [[2 3 4]
 [5 6 7]]

Dimension of array  is             :  2
No of elements in array is         :  6
Data type of array is              :  int64
Size of array in each dimension is :  (2, 3)
Size (in bytes) of array is        :  8
Memory location  of array is       :  <memory at 0x7938f3ebfb90>


In [ ]:
a3 = np.array((1,2,3))
print(a3)

[1 2 3]


# Numpy Array Indexing
Each element in an array is identified by its corresponding array index.

array[index]

array[start:stop]

array[start:stop:step]


### Accessing Array elements using Index

In [ ]:
arr1 = np.array([2,4,6,8,10])
print(arr1)

[ 2  4  6  8 10]


In [ ]:
# Displaying array elements in index 1 and 3
print("Element in index 1 : ", arr1[1])
print("Element in index 3 : ",arr1[3])

Element in index 1 :  4
Element in index 3 :  8


### Accessing Array elements using Negative Index

In [ ]:
arr1 = np.array([2,4,6,8,10])
print("Elements in the array  : ", arr1)

print("Element in index -2 is : ",arr1[-2])

Elements in the array  :  [ 2  4  6  8 10]
Element in index -2 is :  8


### Modifying Array elements using Indexing and Negative Indexing

In [ ]:
arr1 = np.array([2,4,6,8,10])
print("Before Modification                             : ", arr1)

arr1[2] = 0
print("After Modification using indexing [2]           : ", arr1)

arr1[-5] = 1
print("After Modification using negative indexing [-5] : ", arr1)

Before Modification                             :  [ 2  4  6  8 10]
After Modification using indexing [2]           :  [ 2  4  0  8 10]
After Modification using negative indexing [-5] :  [ 1  4  0  8 10]


### 2D Array Indexing
specify the row index and column index of the element

array[row_index , col_index]

In [ ]:
arr2 = np.array([[0,2,4,6,8],[1,3,5,7,9]])
print(arr2)

print("\nAccessing Elements using indexing")
print("Row 2, Column 3 is : ",arr2[1,2])

print("\nAccessing Elements using negative indexing")
print("Row 1, Column 4 is : ",arr2[-2,-4])


[[0 2 4 6 8]
 [1 3 5 7 9]]

Accessing Elements using indexing
Row 2, Column 3 is :  5

Accessing Elements using negative indexing
Row 1, Column 4 is :  2


### 3D Array Indexing
array[slice , row, col]

In [ ]:
# create a 3D array with shape (2, 3, 4)
a3 = np.array([[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]],

                    [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])

print("Elements in the 3D array\n",a3)


# accessing and printing a specific element of the array
print("\nElement (1,2,1) in 3D array is :",a3[1, 2, 1])

Elements in the 3D array
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Element (1,2,1) in 3D array is : 22


In [ ]:
a4 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

               [[13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24]]])

# NumPy Array Slicing
process of extracting a portion of an array




## 1D array
array[start:end:step]

end and step are optional

In [ ]:
s1arr =  np.array([1,2,3,4,5,6,7,8,9])
print(s1arr)

[1 2 3 4 5 6 7 8 9]


### Different combinations of start, end , step and negative slicing

In [ ]:
print(s1arr[1:5])

[2 3 4 5]


In [ ]:
print(s1arr[0:5:2])

[1 3 5]


In [ ]:
print(s1arr[:6:])

[1 2 3 4 5 6]


In [ ]:
print(s1arr[1::])

[2 3 4 5 6 7 8 9]


In [ ]:
print(s1arr[::3])

[1 4 7]


In [ ]:
print(s1arr)           # print all the elements
print(s1arr[-3:])      # print with negative start slicing
print(s1arr[-5:-2])    # print with negative slicing
print(s1arr[-1::-2])   # print from reverse with step
print(s1arr[::-1])     # reverse array

[1 2 3 4 5 6 7 8 9]
[7 8 9]
[5 6 7]
[9 7 5 3 1]
[9 8 7 6 5 4 3 2 1]


## 2D array
array[row_start : row_end , col_start : col_end ]

end is optional

In [ ]:
s2arr = np.array([[1,2,3,4],[5,6,7,8],[0,2,4,6],[1,3,5,7]])
print(s2arr)

[[1 2 3 4]
 [5 6 7 8]
 [0 2 4 6]
 [1 3 5 7]]


In [ ]:
print(s2arr[1:,])

[[5 6 7 8]
 [0 2 4 6]
 [1 3 5 7]]


In [ ]:
print(s2arr[:,2:])

[[3 4]
 [7 8]
 [4 6]
 [5 7]]


In [ ]:
print(s2arr[:,2:3])

[[3]
 [7]
 [4]
 [5]]


## 3D array
array[slice_start : slice_end , row_start : row_end , col_start : col_end ]

end  optional

In [ ]:
s3arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(s3arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [ ]:
print(s3arr[0, 1, 1:4])

[7 8 9]


# NumPy Array Reshaping
changing the shape of an array without changing its data

1D array
```
[1,2,3,4,5,6,7,8]
```

2D array
```
[1,2,3,4]
[5,6,7,8]
```

3D array
```
[
  [
  [1 2]
  [3 4]
  ]

 [
  [5 6]
  [7 8]
  ]
]
```


## np.reshape(array, newshape)

In [ ]:
# 1D array
rearr = np.arange(8)
print(rearr)

[0 1 2 3 4 5 6 7]


In [ ]:
# 2D array with shape 2 x 4
rarr = np.arange(8)
re2arr = np.reshape(rarr,(2,4))
print(re2arr)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
# 2D array with shape 4 x 2
r2arr = np.arange(8).reshape((4,2))
print(r2arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [ ]:
# 3D array
re3arr = np.arange(8).reshape(2,2,2)
print(re3arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## Flatten N-d Array to 1-D Array Using reshape()
converting a multidimensional array into a 1D array

pass "-1" as an argument to reshape()


In [ ]:
# flatten 2D array to 1D
f2arr = np.array([[1, 3], [5, 7], [9, 11]])
f2 = np.reshape(f2arr, -1)
print("2D array :\n", f2arr)
print("\nFlattened 2D array:", f2)

# flatten 3D array to 1D
f3arr = np.array([[[1, 3], [5, 7]], [[2, 4], [6, 8]]])
f3 = np.reshape(f3arr, -1)
print("\n3D array : \n", f3arr)
print("\nFlattened 3D array:", f3)

2D array :
 [[ 1  3]
 [ 5  7]
 [ 9 11]]

Flattened 2D array: [ 1  3  5  7  9 11]

3D array : 
 [[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]

Flattened 3D array: [1 3 5 7 2 4 6 8]


# NumPy Array – Iterate over elements (nditer)
 visit each of the element in the numpy array

In [ ]:
iarr = np.arange(9).reshape(3,3)

# Print array
print("The array\n",iarr)

The array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print("\nIterating over the array")

for x in iarr:
	print(x,end=' ')

print("\n\nIterating over all the elemnets of array")

for x in np.nditer(iarr):
	print(x,end=' ')



Iterating over the array
[0 1 2] [3 4 5] [6 7 8] 

Iterating over all the elemnets of array
0 1 2 3 4 5 6 7 8 

# NumPy Array Functions
built-in functions provided by NumPy that allow us to create and manipulate arrays, and perform different operations on them


Array Creation Functions  -	np.array(), np.zeros(), np.ones(), np.empty(), etc.

Array Manipulation Functions	- np.reshape(), np.transpose(), etc.

Array Mathematical Functions	- np.add(), np.subtract(), np.sqrt(), np.power(), etc.

Array Statistical Functions	- np.median(), np.mean(), np.std(), and np.var().

Array Comparison Functions - np.less(), np.less_equal(), greater(), etc

Array Logical Functions    - np.logical_and(), np.logical_or(), np.logical_not

Array Input and Output Functions	- np.save(), np.load(), np.loadtxt(), etc.


In [71]:
# manipulation function
# np.transpose(source_array)

tarr = np.array([0,2,4,6,8,1,3,5,7,9]).reshape(2,5)
print(tarr)

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [72]:
ntarr = np.transpose(tarr)
print(ntarr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [76]:
# mathematical function add(),subtract(), multiply(), divide(), power(), sqrt()

a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 9, 16, 25, 36])

# add the two arrays element-wise
arr_sum = np.add(a, b)

# subtract b from a element-wise
arr_diff = np.subtract(a, b)

# multiply a and b element-wise
arr_mult = np.multiply(a, b)

# divide a by b element-wise
arr_divi = np.divide(a, b)

# power of a element-wise
arr_pow = np.power(a,3)

# square root of b element-wise
arr_sqrt = np.sqrt(b)

print("\nArray a          :", a)
print("\nArray b          :", b)
print("\nAddition         :", arr_sum)
print("\nSubtraction      :", arr_diff)
print("\nMultiplication   :", arr_mult)
print("\nDivision         :", arr_divi)
print("\nPower of a       :", arr_pow)
print("\nSquare root of b :", arr_sqrt)



Array a          : [1 2 3 4 5]

Array b          : [ 4  9 16 25 36]

Addition         : [ 5 11 19 29 41]

Subtraction      : [ -3  -7 -13 -21 -31]

Multiplication   : [  4  18  48 100 180]

Division         : [0.25       0.22222222 0.1875     0.16       0.13888889]

Power of a       : [  1   8  27  64 125]

Square root of b : [2. 3. 4. 5. 6.]


In [77]:
# Statistical Functions mean() , median(), std(), percentile(), min(), max()


marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)
print("Mean:",mean_marks)

# compute the median of marks
median_marks = np.median(marks)
print("Median:",median_marks)

# compute the standard deviation of marks
std_marks = np.std(marks)
print("Standard Deviation:",std_marks)

# compute the percentile of marks
percen_marks1 = np.percentile(marks,25)
print("25th percentile:",percen_marks1)
percen_marks2 = np.percentile(marks,75)
print("75th percentile:",percen_marks2)

# find the minimum and maximum marks
min_marks = np.min(marks)
print("Minimum marks:", min_marks)

max_marks = np.max(marks)
print("Maximum marks:", max_marks)

Mean: 77.2
Median: 78.0
Standard Deviation: 6.368673331236263
25th percentile: 76.0
75th percentile: 81.0
Minimum marks: 66
Maximum marks: 85


In [80]:
# Array Comparison Functions - np.less(), np.less_equal(), greater(), greater_equal(), equal(), not_equal()

f = np.array([9, 12, 21])
s = np.array([21, 12, 9])

print("First Array          :",f)
print("Second Array         :",s)

# use of less()
l = np.less(f, s)
print("Using less()         :",l)

# use of less_equal()
le = np.less_equal(f, s)
print("Using less_equal()   :",le)     # Output: [ True  True False]

# use of greater()
g = np.greater(f, s)
print("Using greater()      :",g)    # Output: [False False  True]

# use of greater_equal()
ge = np.greater_equal(f, s)
print("Using greater_equal():",ge)    # Output: [False  True  True]

# use of equal()
e = np.equal(f, s)
print("Using equal()        :",e)    # Output: [False  True False]

# use of not_equal()
ne = np.not_equal(f, s)
print("Using not_equal()    :",ne)    # Output: [ True False  True]

First Array          : [ 9 12 21]
Second Array         : [21 12  9]
Using less()         : [ True False False]
Using less_equal()   : [ True  True False]
Using greater()      : [False False  True]
Using greater_equal(): [False  True  True]
Using equal()        : [False  True False]
Using not_equal()    : [ True False  True]


In [82]:
# Array Logical Functions - np.logical_and(), np.logical_or(), np.logical_not

x = np.array([True, False, True])
y = np.array([False, False, True])

print("First Array       :",x)
print("Second Array      :",y)

# Logical AND
print("Logical AND       :",np.logical_and(x, y)) # Output: [False False  True]

# Logical OR
print("Logical OR        :",np.logical_or(x, y)) # Output: [ True False  True]

# Logical NOT
print("Logical NOT       :",np.logical_not(x)) # Output: [False  True False]

First Array       : [ True False  True]
Second Array      : [False False  True]
Logical AND       : [False False  True]
Logical OR        : [ True False  True]
Logical NOT       : [False  True False]


In [84]:
# Array Input/Output Functions savetxt() , loadtxt()

# create an array
arr = np.array([[1, 3, 5], [2, 4, 6]])

# save the array to a text file
np.savetxt('data1.txt', arr)

# load the data from the text file
loaded_data = np.loadtxt('data1.txt')

# print the loaded data
print(loaded_data)

[[1. 3. 5.]
 [2. 4. 6.]]


#Ms.K.Kiruthika
#Technical Trainer
#T & P Cell
#K.S.Rangasamy College of Technology







